readline: remove patch-status from ERROR_QA
* both patches in meta-gplv2 are fine:
  recipes-core/readline/readline-5.2/configure-fix.patch:Upstream-Status: Pending
  recipes-core/readline/readline-5.2/fix-redundant-rpath.patch:Upstream-Status: Inappropriate

* but there are 14 patches fetched from GNU_MIRROR like:
  ${GNU_MIRROR}/readline/readline-5.2-patches/readline52-001;name=patch1;apply=yes;striplevel=0
  which obviously don't have OE specific Upstream-Status tags and cause 14 errors like:

  ERROR: lib32-readline-5.2-r9 do_patch: QA Issue: Missing Upstream-Status in patch
  downloads/readline52-001
  Please add according to https://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines#Patch_Header_Recommendations:_Upstream-Status . [patch-status]

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>